---
name: Lint
"on":
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    lint:
        runs-on: ubuntu-latest
        env:
            MNEMONIC: ${{secrets.MNEMONIC}}
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Install Node.js
              uses: actions/setup-node@v3
            - name: Install the Node.js dependencies
              run: npm i
            - name: Lint the contracts
              run: npm run lint
            - name: Add lint summary
              run: |
                  echo "## Lint" >> $GITHUB_STEP_SUMMARY
                  echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
