---
name: Unit Tests
"on":
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    test:
        runs-on: ubuntu-latest
        env:
            MNEMONIC: ${{secrets.MNEMONIC}}
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Install Node.js
              uses: actions/setup-node@v3
            - name: Install the Node.js dependencies
              run: npm i
            - name: Install Foundry
              uses: onbjerg/foundry-toolchain@v1
              with:
                  version: nightly
            - name: Show the Foundry config
              run: forge config
            - name: Run the tests
              run: forge test
            - name: Add test summary
              run: |
                  echo "## Tests" >> $GITHUB_STEP_SUMMARY
                  echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
